:icons:
:imagesdir: ../images

== Thèmes
Plugin for creating themes for the Design mode from the library Bootstrap

=== Description

*_Jeedom_*(TM) Design ™ offers a mode that allows to create a free mode of view, but is not affordable for anyone, the purpose of the plugin is to create the template of your Design mode, so that the only actions to do in Design view is the placement of widgets. The template includes a menu bar for selecting the "room" that we want to see in main frame, a main frame  will display the "room" asked and optional tray. +
As with the development came this are grafted several other modules that complement the plugin, but can be used as completely independent way for other plugin or functionality *_Jeedom_*(TM).

. Images Manager
. Custom Buttons

Other modules may be implemented according to the needs of the community.

[icon="../images/tip.png"]
[TIP]
The plugin is oriented to be taken as simply as possible, there is no need to know all the options for use, the default configuration is sufficient for tablet use. Just create a theme to add buttons to make it all usable on.

[icon="../images/important.png"]
[IMPORTANT]
the plugin will not create it alone design mode, you have before you start to get an idea of what you want to do, various examples are findable on the official forum of *_Jeedom_*(TM) that can give an idea of the possibility of Design mode.

'''
=== Creating a Easy Theme
include::partie_1.asciidoc[Creating a Easy Theme]

'''
=== Advanced Options
include::partie_2.asciidoc[Advanced Options]

'''
=== Additional modules
include::partie_3.asciidoc[Additional modules]

'''
=== FAQ
include::faq.asciidoc[]

'''
=== Changelog
include::changelog.asciidoc[]
