:icons:
:imagesdir: ../images

[role="h1"]
Thèmes - Version 1.8.3

[role="text-justify"]
--
Plugin servant à créer des thèmes pour le mode Design à partir de la librairie Bootstrap
--

[role="col-md-12"]
{nbsp} +

== Description

[role="col-md-12 text-justify"]
--
*_Jeedom_*(TM) nous offre un mode Design qui permet de créer un mode de vue très libre, mais n'est pas abordable pour n'importe qui, le but de se plugin est de créer la structure complète de votre mode Design, pour que les seuls actions à faire en mode Design soit le placement des widgets. La structure comprend une barre de menu permettant de sélectionner la "pièce" que l'on veut visualiser, un cadre principale ou sera afficher la "pièce" demandé, une barre d'état optionnelle +
Au fur et à mesure du développement sont venu ce greffer plusieurs autres modules qui viennent en complément du plugin, mais qui pourront servir de manière complètement indépendantes pour d'autres plugin ou fonctionnalité de *_Jeedom_*(TM)

. Le gestionnaires d'images
. Les boutons Personnalisés
--

[role="col-md-12 text-justify"]
--
[icon="../images/tip.png"]
[TIP]
Le Plugin est orienté pour être pris en main le plus simplement possible, il n'y a aucun besoin de connaître toutes les options pour l'utiliser, la configuration par défaut suffit pour une utilisation sur tablette. Il suffit de créer un thème de rajouter des boutons pour qu'il soit tout de suite utilisable. +

[icon="../images/important.png"]
[IMPORTANT]
le plugin ne va pas créer le mode design tout seul, il faut avant de commencer avoir une idée de ce que l'on veut faire, divers exemples sont trouvable sur le forum officiel de *_Jeedom_*(TM) qui peuvent donner une idée des possibilité du mode Design
--

[role="col-md-12"]
{nbsp} +

=== Vidéo(s)

Un tutoriel vidéo est aussi disponible, merci à *SBO* +
https://www.youtube.com/watch?v=alpuGohpuXE&feature=youtu.be

include::partie_1.asciidoc[Création d'un thème Facile]

'''
== FAQ
include::faq.asciidoc[]

'''
== Changelog
include::changelog.asciidoc[]
