== Thèmes
Plugin servant à creer des thèmes pour le mode Design à partir de la librairie Bootstrap

=== Description
*_Jeedom_*(TM) nous offre un mode Design qui permet de creer un mode de vue très libre, mais n'est pas abordable pour n'importe qui, le but de se plugin est de créer la structure compléte de votre mode Design, pour que les seuls actions à faire en mode Design soit le placement des widgets. +
Au fur et à mesure du développement sont venu ce gréffer plusieurs autres modules qui viennent en complément du plugin, mais qui pourront servir de manière complétement indépendantes pour d'autres plugin ou fonctionnalité de *_Jeedom_*(TM)

. Le gestionnaires d'images
. Les boutons Personnalisés

D'autres modules pourront être implémenter selon les besoins de la communauté

TIP:
Le Plugin est orienté pour être pris en main le plus simplement possible, il n'y a aucun besoin de connaître toutes les options pour l'utiliser, la configuration par défaut suffit pour une utilisation sur tablette. Il suffit de créer un thème de rajouter des boutons pour qu'il soit tout de suite utilisable.


.Attention
----
le plugin ne va pas créer le mode design tout seul, il faut avant de commencer avoir une idée de ce que l'on veut faire, divers exemples sont trouvable sur le forum officiel de Jeedom qui peuvent donner une idée des possibilité du mode Design
----

'''
=== Création d'un thème Facile
include::partie_1.asciidoc[Création d'un thème Facile]

'''
=== Options avancées
include::partie_2.asciidoc[Options avancées]

'''
=== Modules additionnels
include::partie_3.asciidoc[]

'''
=== FAQ
include::faq.asciidoc[]

'''
=== Changelog
include::changelog.asciidoc[]
