:icons:
:imagesdir: ../images

[role="h1"]
Thèmes - Version 1.8.3

[role="text-justify"]
--
Plugin pour créer des thèmes pour le mode Design à partir de la bibliothèque Bootstrap.
--

[role="col-md-12"]
{nbsp} +

== Description

[role="col-md-12 text-justify"]
--
*_Jeedom_*(TM) nous offre un mode Design qui permet de créer un mode de vue très libre, mais n'est pas abordable pour n'importe qui. Le but de ce plugin est de créer la structure complète de votre mode Design, pour que les seules actions à faire en mode Design soient le placement des widgets. La structure comprend une barre de menu permettant de sélectionner la "pièce" que l'on veut visualiser,
un cadre principal ou sera affiché la "pièce" demandée et une barre d'état optionnelle. +
Au fur et à mesure du développement sont venus se greffer plusieurs autres modules qui viennent en complément du plugin, mais qui pourront servir de manière complètement indépendante pour d'autres plugins ou fonctionnalités de *_Jeedom_*(TM).

. Le gestionnaire d'images
. Les boutons personnalisés
--

[role="col-md-12 text-justify"]
--
[icon="../images/tip.png"]
[TIP]
Le plugin est orienté pour être pris en main le plus simplement possible, il n'y a aucun besoin de connaître toutes les options pour l'utiliser, la configuration par défaut suffit pour une utilisation sur tablette. Il suffit de créer un thème et de rajouter des boutons pour qu'il soit tout de suite utilisable. +

[icon="../images/important.png"]
[IMPORTANT]
Le plugin ne va pas créer le mode design tout seul, il faut avant de commencer avoir une idée de ce que l'on veut faire, divers exemples sont disponibles sur le forum officiel de *_Jeedom_*(TM) qui peuvent donner une idée des possibilités du mode Design.
--

[role="col-md-12"]
{nbsp} +

=== Vidéo(s)

Un tutoriel vidéo est aussi disponible, merci à *SBO* +
https://www.youtube.com/watch?v=alpuGohpuXE&feature=youtu.be

include::partie_1.asciidoc[]

'''
== FAQ
include::faq.asciidoc[]
